apiVersion: v1
kind: Service
metadata:
  name: {{ Chart.Name }}
  labels:
    app: {{ Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
  selector:
    app.kubernetes.io/instance: {{ Chart.Name }}
    app.kubernetes.io/name: {{ Chart.Name }}
